management.endpoints.web.exposure.include: "*"
spring:
  application:
    name: mitac-fia-demo
  boot:
    admin:
      client:
        url: http://sba-server.test.svc.cluster.local:8081
        instance:
          service-url: http://mitac-fia-demo.test.svc.cluster.local:8080

---
spring:
  profiles: oracle
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: username
    password: password
